### ISSUE TITLE
API 23 changes potentially unimplemented

### ISSUE THREAD

**Issue by pbanwait** [ukanth/XPrivacy#1]
From a quick check on @M66B's XPrivacy repo, it seems that there were no API changes implemented from 22 to 23.

Android M was first unveiled on May 28, 2015 with official release on October 5, 2015. Additionally, the [API Diff Spec](https://developer.android.com/sdk/api_diff/23/changes.html ) is dated October 14, 2015. The commits on the official XPrivacy repo's [source folder](https://github.com/M66B/XPrivacy/commits/master/src/biz/bokhorst/xprivacy) do not show any diffs/commits relevant to API changes for Marshmallow. The latest commits address changes for Lollipop only.

Edit: An example of an API 23 class without XPrivacy coverage is [`NetworkStatsManager`](https://developer.android.com/sdk/api_diff/23/changes/pkg_android.app.usage.html). This class provides access to network usage and history. I cannot find any references in official XPrivacy relating to that class and its methods. I will explore more when possible. Note, that a similar class, `UsageStatsManager`, in that package `android.app.usage`, is covered by XPrivacy via an `XHook` subclass named `XUsageStatsManager`.

**Comment by M66B** [comment]
To save you effort: Lollipop was indeed the last version XPrivacy was really updated for.

**Comment by da-bernie** [comment]
Hello pbanwait,

it would be great if you could support us collecting the necessary information for an update of xprivacy.
I have already started reading the documentation. There are two wiki-pages about the [Android-API](https://github.com/ukanth/XPrivacy/wiki/Android-API) and the [Google APIs for Android](https://github.com/ukanth/XPrivacy/wiki/Google-APIs-for-Android) where I collect the results.

The changes adding API's to Android are checked completely, the next step for me would be to read the Google API. The last big thing would be to check the API 27 completely to cover all the changes from 22 to 27.

Best regards

da-bernie

**Comment by pbanwait** [comment]
Given the existence of XPrivacyLua, (amazing work @M66B), closing this issue. @ukanth you should probably close this fork or link to XPrivacyLua.
